[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar.default]
background_opacity = 0.59999998658895493
capsule = true
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "battery", "control-center" ]
margin_edge = 8
margin_ends = 200
padding = 6
radius = 80
start = [ "launcher", "workspaces", "media" ]

[control_center]
width = 900

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 18000

[location]
sunrise = "04:00"
sunset = "20:30"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
enabled = true
start_time = "20:30"
stop_time = "04:00"
temperature_night = 5000
use_weather_location = false

[notification]
background_opacity = 0.59999998658895493

[osd]
background_opacity = 0.59999998658895493
lock_keys = false
position = "top_right"

    [osd.kinds]
    media = false

[shell]
avatar_path = "/data/Photos and Videos/download.png"
font_family = "Adwaita Sans"
polkit_agent = true
telemetry_enabled = false

    [shell.animation]
    speed = 0.90000000000000002

    [shell.panel]
    control_center_placement = "floating"
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

[theme]
builtin = "Catppuccin"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4" ]
    community_ids = [ "yazi" ]

[wallpaper]
directory = "/data/Photos and Videos/Wallpapers"
transition = [ "disc", "honeycomb", "wipe" ]
transition_duration = 4000
transition_on_startup = true

    [wallpaper.default]
    path = "/data/Photos and Videos/Wallpapers/a_clouds_in_the_sky.png"

    [wallpaper.last]
    path = "/data/Photos and Videos/Wallpapers/a_clouds_in_the_sky.png"

    [wallpaper.monitors.LVDS-1]
    path = "/data/Photos and Videos/Wallpapers/117497448_p0.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/data/Photos and Videos/Wallpapers/a_clouds_in_the_sky.png"

[weather]
enabled = false

[widget.battery]
display_mode = "icon"
show_label = false

[widget.bluetooth]
show_label = false

[widget.launcher]
custom_image = "/data/Photos and Videos/arch logo.png"
custom_image_colorize = true
scale = 1.3500000000000001

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"
