## SwayFX Configs

# Rounded Corners
corner_radius 20

# Blur
# blur enable
# blur_radius 3
# blur_passes 2

# Shadows
# shadows enable
# shadow_blur_radius 10
# shadow_color #00000088
# shadow_offset 0 4

# Dimming Unfocused Window
default_dim_inactive 0.1

