# --- Renderer & API ---
profile=high-quality
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

# --- Upscaling & Quality ---
scale=ewa_lanczossharp
scale-antiring=0.6
cscale=spline36
dscale=mitchell

deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=5

# --- Playback & Window ---
save-position-on-quit=yes
fullscreen=yes
volume=100

video-sync=display-resample
interpolation=yes
tscale=oversample

[4K-Fallback]
profile-cond=(width >= 3840 or height >= 2160)
profile-restore=copy

interpolation=no
video-sync=audio
deband=no

