profile=fast

vo=gpu
gpu-api=opengl

hwdec=auto-safe

scale=bilinear
cscale=bilinear
dscale=bilinear

save-position-on-quit=yes


# HEVC PROFILE
[hevc-mode]
profile-cond=video_format == 'hevc'
profile-restore=copy

hwdec=no

framedrop=decoder+vo

video-sync=audio
interpolation=no

