###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$browser = firefox
$fileManager = nautilus
$menu = ~/.config/rofi/launchers/type-2/launcher.sh || pkill rofi
$screenshot_area = grim -g "$(slurp)" - | wl-copy
$screenshot_full = grim - | wl-copy
$clipboard = cliphist list | rofi -dmenu
$emoji = rofi -show emoji

